//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageCompany.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsDispalyed {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsDispalyed() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StorageCompany.Ressources.StringsDispalyed", typeof(StringsDispalyed).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce champ est requis.
        /// </summary>
        public static string error_requiredFields {
            get {
                return ResourceManager.GetString("error_requiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format de la date non valide.
        /// </summary>
        public static string error_wrongDateFormat {
            get {
                return ResourceManager.GetString("error_wrongDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compte client.
        /// </summary>
        public static string table_account {
            get {
                return ResourceManager.GetString("table_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville.
        /// </summary>
        public static string table_account_city {
            get {
                return ResourceManager.GetString("table_account_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pays.
        /// </summary>
        public static string table_account_country {
            get {
                return ResourceManager.GetString("table_account_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mail.
        /// </summary>
        public static string table_account_email {
            get {
                return ResourceManager.GetString("table_account_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro d&apos;entreprise.
        /// </summary>
        public static string table_account_entrepriseNumber {
            get {
                return ResourceManager.GetString("table_account_entrepriseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entreprise interne.
        /// </summary>
        public static string table_account_intern {
            get {
                return ResourceManager.GetString("table_account_intern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du compte client.
        /// </summary>
        public static string table_account_name {
            get {
                return ResourceManager.GetString("table_account_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code postal.
        /// </summary>
        public static string table_account_postalCode {
            get {
                return ResourceManager.GetString("table_account_postalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de la rue.
        /// </summary>
        public static string table_account_streetName {
            get {
                return ResourceManager.GetString("table_account_streetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro de rue.
        /// </summary>
        public static string table_account_streetNumber {
            get {
                return ResourceManager.GetString("table_account_streetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Article.
        /// </summary>
        public static string table_item {
            get {
                return ResourceManager.GetString("table_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date d&apos;expiration.
        /// </summary>
        public static string table_item_timeExpire {
            get {
                return ResourceManager.GetString("table_item_timeExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mouvement.
        /// </summary>
        public static string table_movement {
            get {
                return ResourceManager.GetString("table_movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de stockage.
        /// </summary>
        public static string table_movement_dateDone {
            get {
                return ResourceManager.GetString("table_movement_dateDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvel emplacement.
        /// </summary>
        public static string table_movement_newStorage {
            get {
                return ResourceManager.GetString("table_movement_newStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ancien emplacement.
        /// </summary>
        public static string table_movement_oldStorage {
            get {
                return ResourceManager.GetString("table_movement_oldStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Produit.
        /// </summary>
        public static string table_movement_product {
            get {
                return ResourceManager.GetString("table_movement_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statut.
        /// </summary>
        public static string table_movement_status {
            get {
                return ResourceManager.GetString("table_movement_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date d&apos;expiration.
        /// </summary>
        public static string table_movement_timeExpire {
            get {
                return ResourceManager.GetString("table_movement_timeExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commande.
        /// </summary>
        public static string table_order {
            get {
                return ResourceManager.GetString("table_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destinataire.
        /// </summary>
        public static string table_order_accountRecipient {
            get {
                return ResourceManager.GetString("table_order_accountRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expéditeur.
        /// </summary>
        public static string table_order_accountSender {
            get {
                return ResourceManager.GetString("table_order_accountSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de la commande.
        /// </summary>
        public static string table_order_dateAsked {
            get {
                return ResourceManager.GetString("table_order_dateAsked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date effective de livraison.
        /// </summary>
        public static string table_order_dateDone {
            get {
                return ResourceManager.GetString("table_order_dateDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de la demande de livraison.
        /// </summary>
        public static string table_order_dateEstimated {
            get {
                return ResourceManager.GetString("table_order_dateEstimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interne.
        /// </summary>
        public static string table_order_intern {
            get {
                return ResourceManager.GetString("table_order_intern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string table_order_type {
            get {
                return ResourceManager.GetString("table_order_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paquet.
        /// </summary>
        public static string table_package {
            get {
                return ResourceManager.GetString("table_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hauteur du paquet.
        /// </summary>
        public static string table_package_height {
            get {
                return ResourceManager.GetString("table_package_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Longueur du paquet.
        /// </summary>
        public static string table_package_length {
            get {
                return ResourceManager.GetString("table_package_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du paquet.
        /// </summary>
        public static string table_package_name {
            get {
                return ResourceManager.GetString("table_package_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Poids maximal du paquet.
        /// </summary>
        public static string table_package_weight {
            get {
                return ResourceManager.GetString("table_package_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Largeur du paquet.
        /// </summary>
        public static string table_package_width {
            get {
                return ResourceManager.GetString("table_package_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Produit.
        /// </summary>
        public static string table_product {
            get {
                return ResourceManager.GetString("table_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description du produit.
        /// </summary>
        public static string table_product_description {
            get {
                return ResourceManager.GetString("table_product_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du produit.
        /// </summary>
        public static string table_product_name {
            get {
                return ResourceManager.GetString("table_product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stock minimum.
        /// </summary>
        public static string table_product_stockMax {
            get {
                return ResourceManager.GetString("table_product_stockMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stock maximum.
        /// </summary>
        public static string table_product_stockMin {
            get {
                return ResourceManager.GetString("table_product_stockMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Role.
        /// </summary>
        public static string table_role_name {
            get {
                return ResourceManager.GetString("table_role_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description du status.
        /// </summary>
        public static string table_status_description {
            get {
                return ResourceManager.GetString("table_status_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clôture de l&apos;état.
        /// </summary>
        public static string table_status_endingStatus {
            get {
                return ResourceManager.GetString("table_status_endingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du status.
        /// </summary>
        public static string table_status_name {
            get {
                return ResourceManager.GetString("table_status_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stockage.
        /// </summary>
        public static string table_storage {
            get {
                return ResourceManager.GetString("table_storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du stock.
        /// </summary>
        public static string table_storage_name {
            get {
                return ResourceManager.GetString("table_storage_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Emplacement utilisable.
        /// </summary>
        public static string table_storage_usable {
            get {
                return ResourceManager.GetString("table_storage_usable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de stockage.
        /// </summary>
        public static string table_storageType {
            get {
                return ResourceManager.GetString("table_storageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description du stock.
        /// </summary>
        public static string table_storageType_description {
            get {
                return ResourceManager.GetString("table_storageType_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hauteur maximum.
        /// </summary>
        public static string table_storageType_maxHeight {
            get {
                return ResourceManager.GetString("table_storageType_maxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Longueur maximum.
        /// </summary>
        public static string table_storageType_maxLength {
            get {
                return ResourceManager.GetString("table_storageType_maxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Poids maximum.
        /// </summary>
        public static string table_storageType_maxWeight {
            get {
                return ResourceManager.GetString("table_storageType_maxWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Largeur maximum.
        /// </summary>
        public static string table_storageType_maxWidth {
            get {
                return ResourceManager.GetString("table_storageType_maxWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du type de stock.
        /// </summary>
        public static string table_storageType_name {
            get {
                return ResourceManager.GetString("table_storageType_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        public static string table_user_firstname {
            get {
                return ResourceManager.GetString("table_user_firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string table_user_name {
            get {
                return ResourceManager.GetString("table_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        public static string table_user_password {
            get {
                return ResourceManager.GetString("table_user_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur.
        /// </summary>
        public static string table_user_username {
            get {
                return ResourceManager.GetString("table_user_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion de stock.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création d&apos;un compte client.
        /// </summary>
        public static string title_account_create {
            get {
                return ResourceManager.GetString("title_account_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression d&apos;un compte client.
        /// </summary>
        public static string title_account_delete {
            get {
                return ResourceManager.GetString("title_account_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description d&apos;un compte client.
        /// </summary>
        public static string title_account_details {
            get {
                return ResourceManager.GetString("title_account_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Édition d&apos;un compte client.
        /// </summary>
        public static string title_account_edit {
            get {
                return ResourceManager.GetString("title_account_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des comptes client.
        /// </summary>
        public static string title_account_index {
            get {
                return ResourceManager.GetString("title_account_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encodage.
        /// </summary>
        public static string title_encoding {
            get {
                return ResourceManager.GetString("title_encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        public static string title_home {
            get {
                return ResourceManager.GetString("title_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inventaire.
        /// </summary>
        public static string title_inventory {
            get {
                return ResourceManager.GetString("title_inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création d&apos;article.
        /// </summary>
        public static string title_item_create {
            get {
                return ResourceManager.GetString("title_item_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression d&apos;article.
        /// </summary>
        public static string title_item_delete {
            get {
                return ResourceManager.GetString("title_item_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description d&apos;article.
        /// </summary>
        public static string title_item_details {
            get {
                return ResourceManager.GetString("title_item_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Édition d&apos;article.
        /// </summary>
        public static string title_item_edit {
            get {
                return ResourceManager.GetString("title_item_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des articles.
        /// </summary>
        public static string title_item_index {
            get {
                return ResourceManager.GetString("title_item_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commande.
        /// </summary>
        public static string title_order {
            get {
                return ResourceManager.GetString("title_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création de paquet.
        /// </summary>
        public static string title_package_create {
            get {
                return ResourceManager.GetString("title_package_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression de paquet.
        /// </summary>
        public static string title_package_delete {
            get {
                return ResourceManager.GetString("title_package_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description de paquet.
        /// </summary>
        public static string title_package_details {
            get {
                return ResourceManager.GetString("title_package_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Édition de paquet.
        /// </summary>
        public static string title_package_edit {
            get {
                return ResourceManager.GetString("title_package_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des paquets.
        /// </summary>
        public static string title_package_index {
            get {
                return ResourceManager.GetString("title_package_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création de produit.
        /// </summary>
        public static string title_product_create {
            get {
                return ResourceManager.GetString("title_product_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression de produit.
        /// </summary>
        public static string title_product_delete {
            get {
                return ResourceManager.GetString("title_product_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description de produit.
        /// </summary>
        public static string title_product_details {
            get {
                return ResourceManager.GetString("title_product_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Édition de produit.
        /// </summary>
        public static string title_product_edit {
            get {
                return ResourceManager.GetString("title_product_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des produits.
        /// </summary>
        public static string title_product_index {
            get {
                return ResourceManager.GetString("title_product_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création d&apos;emplacement.
        /// </summary>
        public static string title_storage_create {
            get {
                return ResourceManager.GetString("title_storage_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression d&apos;emplacement.
        /// </summary>
        public static string title_storage_delete {
            get {
                return ResourceManager.GetString("title_storage_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description d&apos;emplacement.
        /// </summary>
        public static string title_storage_details {
            get {
                return ResourceManager.GetString("title_storage_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Édition d&apos;emplacement.
        /// </summary>
        public static string title_storage_edit {
            get {
                return ResourceManager.GetString("title_storage_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des emplacements.
        /// </summary>
        public static string title_storage_index {
            get {
                return ResourceManager.GetString("title_storage_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création de type d&apos;emplacement.
        /// </summary>
        public static string title_storageType_create {
            get {
                return ResourceManager.GetString("title_storageType_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression de type d&apos;emplacement.
        /// </summary>
        public static string title_storageType_delete {
            get {
                return ResourceManager.GetString("title_storageType_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description de type d&apos;emplacement.
        /// </summary>
        public static string title_storageType_details {
            get {
                return ResourceManager.GetString("title_storageType_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Édition de type d&apos;emplacement.
        /// </summary>
        public static string title_storageType_edit {
            get {
                return ResourceManager.GetString("title_storageType_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Listes des types d&apos;emplacement.
        /// </summary>
        public static string title_storageType_index {
            get {
                return ResourceManager.GetString("title_storageType_index", resourceCulture);
            }
        }
    }
}
